spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.default_schema=${HIBERNATE_DEFAULT_SCHEMA:ai_blog}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.jdbc.time_zone=${HIBERNATE_TIME_ZONE:Europe/Istanbul}
# JWT
jwt.secret=${JWT_SECRET}
jwt.exp=${JWT_EXP:86400000}
# Gemini
gemini.api.key=${GEMINI_API_KEY}
# Mail
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.baseUrl=${APP_BASE_URL:http://localhost:8080/api/auth}